### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by AbooJan** [DarielChen/DCURLRouter#1]
建议添加一个控制器protocol，用于给使用者自定义控制器的初始化。
因为有的控制器可能是从 `xib初始化` 或者是 `storyboard初始化` ，而不是单单纯代码。

而目前作者的代码是简单直接的 alloc, init;
在分类`UIViewController (DCURLRouter)` 第 `89~94` 行。

```
        if(class !=nil){
            VC = [[class alloc]init];
            if([VC respondsToSelector:@selector(open:withQuery:)]){
                [VC open:url withQuery:query];
            }
        }
```

**Comment by expkzb** [comment]
而且 UITableViewController 也不能通过 alloc init 初始化

**Comment by DarielChen** [comment]
由于之前项目都是纯代码,没有考虑支持xib和storyboard,会尽快添加.

**Comment by DarielChen** [comment]
@expkzb 对于这种情况为什么不把控制器直接传进去呢?加载xib和storyboard控制器其实也可以这么做的.
