### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by doubleSkinMilk** [DarielChen/DCURLRouter#2]
建议去掉plist, 这样会让服务端控制更灵活.比如想要在线上跳转一个没有声明在plist里的的控制器  就尴尬了;

**Comment by DarielChen** [comment]
去掉plist文件服务器控制是灵活了,但服务端给的自定义URL通常并不会简单处理后就能变成控制器类名.因为双方都会根据业务逻辑各自命名,所以能有个匹配会比较好.DCURLRouter对没有声明在plist里的控制器会做错误处理.😄

**Comment by doubleSkinMilk** [comment]
这就相当于双方的一个协议,总会有取舍  ;但我还是觉得客户端写一份儿协议 让服务器去遵守 (去掉plist的方式)的方式会好点.

**Comment by wtuyp** [comment]
说实话前几天看到那plist就没往下看了。现在想想自己Fork一份学习并改装下也不错。😂

**Comment by DarielChen** [comment]
@wtuyp 欢迎request
