### ISSUE TITLE
随便说几句关于从哪个 VC push或者 modal 出新的 VC

### ISSUE THREAD

**Issue by JasperYanky** [DarielChen/DCURLRouter#3]
我们的应用做跳转思路上基本和你们的一致。
有个细节是我们所有 modal出的 都是 navigationController  然后实际的 VC 是该 nav 的 rootVC,
以此，在寻找 current VC的时候，从 appdelegate  window的 rootViewController进行判断，是否为 tabbar 或者 nav ,  然后对比 tabbar.selectedViewController(我们应用里面也是一个 nav) / nav 的 nav.visibleViewController != nav.topViewController 就能判断该 nav 有没有 modal 出新的页面, 如果有新的页面 则继续递归出 更上层的 nav.

可能这个方法只限规定好modal 只能 modal 出 nav 的情况. 说的不对请指正：）

**Comment by DarielChen** [comment]
为什么一定要给modal出来的控制器添加一个导航控制器

**Comment by JasperYanky** [comment]
可以在modal的vc上继续push新vc

**Comment by DarielChen** [comment]
DCURLRouter也有给modal出来的控制器添加一个导航控制器的实现,但实际情况中,不一定一定要这样做啊!有可能modal出来的控制器还要继续modal.我觉得应该加一个这个功能.

**Comment by JasperYanky** [comment]
加了nav一样可以modal完了继续modal , 然后还支持继续push 所以我们app里 默认就是modal出nav ,可能需求不一样吧

**Comment by DarielChen** [comment]
但有时会不需要导航条吧

**Comment by JasperYanky** [comment]
隐藏就可以了~  那些自定义 nav 的就是 nav隐藏起来自己写的 view 贴上去的，然后还能继续用 push 和 pop 的方法

**Comment by DarielChen** [comment]
这样也可以😄

**Comment by JasperYanky** [comment]
因为我们有时候 modal 出一个模块可能有扩展，比如拍照，拍照完了还要编辑，还要发布，后面的都是 push 的，所以就默认 modal 出的是 nav 了， 所以可能是需求不一样吧~
