### ISSUE TITLE
关于跨 Tab 跳转的问题

### ISSUE THREAD

**Issue by MrPans** [DarielChen/DCURLRouter#4]
用微信来举例

聊天界面在 `微信` Tab, 通讯录在 `通讯录` Tab，从通讯录中选择一个好友 -> 点击发消息 -> 跳转到 `微信` Tab 并 push 到聊天界面。

像这样的需求，DCURLRouter 能否实现？

**Comment by DarielChen** [comment]
四个步骤:
1. 拿到`微信`的导航控制器
2. 把tab上的selectedViewController设置`微信`导航控制器
3. pop掉`通讯录`中的控制器
4.用`微信`导航控制器进行push操作

DCURLRouter如果做的话只要暴露个属性设置下currentNavigationViewController为`微信`导航控制器,然后就能进行push操作了,但这样做没有必要啊,直接用`微信`导航控制器进行push操作就可以了呀!这也不太符合DCURLRouter设计的初衷啊,DCURLRouter的设计初衷是为了根据服务器给的自定义URL做跳转的.😂

**Comment by MrPans** [comment]
> DCURLRouter的设计初衷是为了根据服务器给的自定义URL做跳转

正是因为这样的设计初衷，所以才会有上面的问题。 上面的问题抽象一下，就是**如何通过 URLRouter 实现从任意界面跳转到任意界面**的问题。

用URLRouter来描述上面微信的例子，就是：
先假定 通讯录中某联系人详情界面的 URL 是`dariel://contact/userA`
聊天界面的 URL 是`dariel://chatdetail/userA`

假如用户现在处于通讯录某个联系人详情界面，然后切到 Safari，输入 `dariel://chatdetail/userA` 。
预期结果应该是跳转到应用的该用户聊天界面。

如果按照你说的四个步骤，

> 1. 拿到微信的导航控制器

第一步 URLRouter 就需要持有 TabbarController 实例，这和 URLRouter 的解耦目的有冲突吧？

如何在不持有任何实例的情况下实现这一的跳转？

**Comment by DarielChen** [comment]
这的确是个好想法, DCURLRouter对于任意界面间跳转的逻辑处理,尤其是TabbarController上不同的导航控制器间的跳转的处理的确是有点问题. 但我不是很明白不持有任何实例是什么情况?push操作需要拿到对应的导航控制器,而TabBarController可以通过根控制器拿到.

Safari的跳转得通过OpenURL去实现.
