### ISSUE TITLE
url传入webview中进行跳转不支持url含有中文和空格

### ISSUE THREAD

**Issue by TPQuietBro** [DarielChen/DCURLRouter#6]
作者你好:
最近项目中用到你的框架,目前发现有两个问题:
1. 如果url中带有中文,会解析不了,找不到映射的控制器
2.如果url中带有空格,也是同样的问题
至于是否有其他不支持的格式,还有待测试验证,希望作者能关注这个问题

**Comment by DarielChen** [comment]
已经能够支持各种字符包括空格了
