### ISSUE TITLE
自定义请求头 换成别的为什么就不行了

### ISSUE THREAD

**Issue by SKYWangyuqi** [DarielChen/DCURLRouter#7]

**Comment by DarielChen** [comment]
你plist文件里面root下的请求头名字没有改过来吧!

**Comment by SKYWangyuqi** [comment]
改了啊

**Comment by SKYWangyuqi** [comment]
就是root下的第三个是个字典  名字改成我要的请求头对吧 我改了 还是不行

**Comment by SKYWangyuqi** [comment]
好像我发现问题了 我请求头里有 _ 好像就不行了

**Comment by SKYWangyuqi** [comment]
大神我还想问一个问题 就是用scheme做跳转 想跳转到指定界面怎么做 很多界面后台都给了url  然后可能我需要跳转到不同的界面 我该怎么弄 是根据传的参数判断吗 ？

**Comment by DarielChen** [comment]
直接把后台给的url当做参数传进去进行跳转.后台给啥就跳转到哪

**Comment by DarielChen** [comment]
现在可以添加各种字符了

**Comment by SKYWangyuqi** [comment]
我让后台把头改了 不过还是很感谢大大的更新 下次用就可以直接用了 谢谢大大
